#pragma once
#include <string>
//ofstream file;
ofstream logfile;
string temp;
//ifstream file1;
//int id;
//int eff;
//Pipe pipe;
//Ks ks;
//string kmMark;
//double len;
string fileName;
//int diam;
//bool isWorking;
//int choose;
int answer;
//string name;
//int amountWorkshops;
//int amountWorkshopsNow;
int answer1;